### ISSUE TITLE
Breakpoints become ghosts

### ISSUE THREAD

**Issue by Kwekker** [btzy/jelly#18]
When either stopping the brainfuck code using "stop" or it crashes because of a runtime error, pretty much every time all breakpoints become _ghosts_.
What I mean by ghosts is that the characters are still red, but you can't remove the breakpoint anymore and  the program doesn't stop there. The only way to remove it (as far as I know) is to delete the character and retype it.

Apart from that btw, this is the best brainfuck compiler/interpreter/debugger I've ever seen, thanks a lot for making it :).

**Comment by btzy** [comment]
Thanks for reporting the issue - I'm glad you like Jelly!

I can't seem to reproduce this, can you tell me your mode (compiled/interpreted, interactive/non-interactive), browser version, and OS version?

Works for me:

https://user-images.githubusercontent.com/6948096/120214481-1edaae00-c267-11eb-8d26-c18a7f218906.mp4

This would probably take a while to get fixed though - I haven't looked at the code for almost four years...
